### ISSUE TITLE
Deployment is no longer reachable

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/itenv_testnet#1]
https://github.com/threefoldtech/tf_operations/issues/138

Deployed a VDC earlier today and 4 hours later was no longer reachable.  Logged the issue in a different repo - will log correctly from now onwards.

**Comment by xmonader** [comment]
Report for newonveda

![image](https://user-images.githubusercontent.com/64129/116239461-f4c33700-a762-11eb-9c62-6cb7009ebe6c.png)


container wid: 35437
kubernetes wid: 35433 on node 8YLrviP78Msue8ptejusq7xxxAgD4ZHNDXXF9KXVGYWr -node got down-
