### ISSUE TITLE
Expiry date of my wallet is not correct

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#11]
I created a VDC silver3 (3bot geertincubaid) on May 14, but the expiration date is already set at June 3. 
I think it has shortened expiration date after the Kubernetes master was down and then re-established, as there were also some alert (ID = 236, see below) that it failed to withdraw about half of the original amount after the reconnect. 

![image](https://user-images.githubusercontent.com/30384423/119099514-43d55280-ba17-11eb-8432-75129ed80554.png)

Alert 234, at moment that connection to Kubernetes master got lost: 
Service vdc_dashboard_k8s_auto_extend raised an exception: Failed to execute: kubectl --kubeconfig /root/.kube/config top nodes --no-headers=true, error was W0520 21:37:41.855560 21393 top_node.go:119] Using json format to get metrics. Next release will switch to protocol-buffers, switch early by passing --use-protocol-buffers flag Unable to connect to the server: dial tcp 185.69.166.147:6443: connect: no route to host

Alert 235, when reconnection was re-established: 
Service vdc_dashboard_zdb_auto_topup raised an exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Alert 236 in the VDC: 
Service vdc_dashboard_provision_wallet_billing raised an exception: Wallet provision_wallet_173e1397a3a149b4b6e39f3d8d0eb52a does not have enough funds to pay for 6.0866467 TFT:GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47

**Comment by AhmedHanafy725** [comment]
The hourly price of the VDC is calculated from the VDC plan price and the number of Kubernetes workers. And there was a race condition while loading the VDC info makes the VDC instance has more workers than the existing ones, So the prepaid wallet drained earlier than normal and affected the VDC expiration.

**Comment by xmonader** [comment]
@gmachtel
