### ISSUE TITLE
creating a new VDC on testnet gives error

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#17]
<img width="901" alt="Screenshot 2021-06-14 at 15 10 03" src="https://user-images.githubusercontent.com/30384423/121897579-d1f4de00-cd22-11eb-85f2-a3b6b6bcf9cb.png">

3bot: geertincubaid

**Comment by xmonader** [comment]
It means the VDC funding wallet that we use, ran out of money
