### ISSUE TITLE
Certification error creating a new VDC

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#18]
I created a new vdc, all deployed well (I think) but last step kept on spinning. Reloading page gives certif error for the url. 

<img width="1068" alt="Screenshot 2021-06-17 at 16 00 54" src="https://user-images.githubusercontent.com/30384423/122412477-e258c300-cf85-11eb-8148-7ffefd40e743.png">

No button 'continue anyway'

3bot: geertincubaid
VDC: silver7

**Comment by gmachtel** [comment]
<img width="790" alt="Screenshot 2021-06-17 at 16 09 04" src="https://user-images.githubusercontent.com/30384423/122413198-79be1600-cf86-11eb-8ccf-c089489bd269.png">

**Comment by hossnys** [comment]
there was some new updates pushed to the server that issuing certificates for vdc , this is fixed now , please verify it .

**Comment by gmachtel** [comment]
Works now !
