### ISSUE TITLE
Traefik in my VDC doesn't run

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#2]
I created a VDC platinum, then added a big worker node. I then tried to deploy a Digibyte node but that failed. 
![image](https://user-images.githubusercontent.com/30384423/116584117-4f9d8f80-a917-11eb-8083-e4f721aec3d3.png)

Retry lead to error message that there were insufficient resources for the gold node, but nothing is deployed on my new VDC !
![image](https://user-images.githubusercontent.com/30384423/116584076-444a6400-a917-11eb-9815-20ec6dbe3067.png)

Looking into Lens gave an error in traefik and an issue with the capacity in k3os 
![image](https://user-images.githubusercontent.com/30384423/116584004-31379400-a917-11eb-8e54-077f55a1e3d8.png)

3bot: geertincubaid
vdc: vdcplatinumnode

**Comment by AhmedHanafy725** [comment]
I think `Traefik` is working fine now in this VDC after updating testnet

![image](https://user-images.githubusercontent.com/41957921/117166240-7b60bf80-adc6-11eb-8444-ece4af5df6de.png)

**Comment by sasha-astiadi** [comment]
@gmachtel please verify

**Comment by gmachtel** [comment]
OK
