### ISSUE TITLE
VDC suddenly disappeared

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#22]
I had a VDC, silver6 running, and I added funding to it. 2 days later, it suddenly disappeared, also from the overview. 

3Bot ID: geertincubaid
VDC: silver6

Presearch node ran on top of it, I received a disconnection notice on July 11, 0:47 UTC.
Additional funding happened on July 9. 

![image](https://user-images.githubusercontent.com/30384423/126158383-af9f0017-2daf-4a1c-900b-5debbf85a679.png)

**Comment by sabrinasadik** [comment]
@xmonader can you take a look at this please?

**Comment by AhmedHanafy725** [comment]
There were issues with pools at that time https://github.com/threefoldtech/home/issues/1102 so it couldn't update the pool with the needed units and the VDC had been gone once the units are finished. (last pool update was 28/6 and it is expired after 14 days 11/7)
![image](https://user-images.githubusercontent.com/41957921/126897853-0ab934c3-0067-4596-9bee-bafc234af767.png)
