### ISSUE TITLE
VM is not shown in dashboard but connects through ip

### ISSUE THREAD

**Issue by namelessperson0** [threefoldtech/itenv_testnet#23]
Deployed a Virtual Machine and connected to it through ssh. 
But the VM does not reflect in the web dashboard.
Tried clicking "Update Dashboard" and loading the page without cache.

**Comment by hossnys** [comment]
this happened because the vm was created with invalid metadata which caused the vm to not be showing on UI , an issue opened for development team to look more deeper into that .

**Comment by namelessperson0** [comment]
> this happened because the vm was created with invalid metadata which caused the vm to not be showing on UI , an issue opened for development team to look more deeper into that .

Can I know which metadata is invalid so that I can avoid it again.
I need to deploy a production app now.

**Comment by namelessperson0** [comment]
The VM is visible now
