### ISSUE TITLE
VDC not shown

### ISSUE THREAD

**Issue by namelessperson0** [threefoldtech/itenv_testnet#24]
My VDC is not visible in https://vdc.testnet.grid.tf/vdc/#/workloads 
However, I am able to access the dashboard. 

Also facing this issue https://github.com/threefoldtech/itenv_testnet/issues/23

**Comment by hossnys** [comment]
@namelessperson0  please provide more info about your vdc name , your threefold_connect name.3bot .

**Comment by hossnys** [comment]
this happened because the node which have the master node of VDC dead and it's redeployed again on a new pool which doesn't have IPV4 units , which make it not showing there , an issue opened for our developers to fix this issue to avoid happening again , thanks for reporting this .

**Comment by namelessperson0** [comment]
@hossnys Should I create a new VDC or continue using the old one?

**Comment by namelessperson0** [comment]
I am able to see the VDC now
