### ISSUE TITLE
OPS; node 8YLrviP78Msue8ptejusq7xxxAgD4ZHNDXXF9KXVGYWr is down and broke megassa's VDC

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/itenv_testnet#3]
![image](https://user-images.githubusercontent.com/64129/116765711-d55c3080-aa26-11eb-9beb-0698d1ee31a7.png)

![image](https://user-images.githubusercontent.com/64129/116765728-e6a53d00-aa26-11eb-8021-a6891411b18f.png)

- 8YLrviP78Msue8ptejusq7xxxAgD4ZHNDXXF9KXVGYWr (hosts the master kubernetes node and the VDC controller)

**Comment by sabrinasadik** [comment]
Node is up & running.

**Comment by sabrinasadik** [comment]
@xmonader is this still relevant or can we close this issue?

**Comment by xmonader** [comment]
@sabrinasadik actually no, because 

![image](https://user-images.githubusercontent.com/64129/117648586-afedc600-b18e-11eb-9af0-cda61a7c52dc.png)

it's not just the node is down, it's also the container got suddenly deleted

**Comment by LeeSmet** [comment]
@xmonader can you please create an issue for this on the zos repo with some details so it can be looked at? After that I'd say this issue can then be closed (with an optional link to the new issue if needed for tracking)

**Comment by xmonader** [comment]
@LeeSmet there you go https://github.com/threefoldtech/zos/issues/1268
