### ISSUE TITLE
Presearch node VDC https://homesteadhacker-presearch-homestead.webg1test.grid.tf/ is down

### ISSUE THREAD

**Issue by homesteadhacker** [threefoldtech/itenv_testnet#4]
It went down sometime in the last 24 hours, after it had been running great for months.  The wallet is funded with 100+ TFT and doesn't expire for some time.  I also can't connect to the VDC here either:

https://vdc.testnet.grid.tf/vdc/#/workloads

...it says "There's an error reaching this VDC.  Please wait if this VDC is deploying or contact support if it is already deployed"

Thanks!

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/116816196-4273e100-ab61-11eb-9605-f55e06acc73c.png)

vdc controller container 26245 got deleted 
```
26245 | Container     | DELETED | freefarm | 13889  | 0.0       | 8zPYak76CXcoZxRoJBjdU69kVjo7XYU1SFE2NEK4UMqn | Up      | OCI runtime create failed: container_linux.go:346: starting container process    |
|       |               |         |          |        |           |                                              |         | caused "process_linux.go:449: container init caused \"rootfs_linux.go:58:        |
|       |               |         |          |        |           |                                              |         | mounting \\\"proc\\\" to rootfs                                                  |
|       |               |         |          |        |           |                                              |         | \\\"/var/cache/modules/flistd/mountpoint/26245-1\\\" at \\\"/proc\\\" caused     |
|       |               |         |          |        |           |                                              |         | \\\"mkdir /var/cache/modules/flistd/mountpoint/26245-1/proc: file exists\\\"\"": |
|       |               |         |          |        |           |                                              |         | unknown                                                                          |
+-------+---------------+---------+----------+--------+-----------+------------

```
and no ip4 units available = the VDC lost its public IP

**Comment by homesteadhacker** [comment]
why?  I didn't delete it.

**Comment by sasha-astiadi** [comment]
@homesteadhacker any confirmatio/could you please review againn? did you delete it?

**Comment by AhmedHanafy725** [comment]
The VDC controller was renewing the plan every week as expected
![image](https://user-images.githubusercontent.com/41957921/117806679-ebee5d00-b25a-11eb-94e7-d8b8af730d44.png)

but the VDC controller got crashed on 17 April, so there was no renew for the plan, and the last renew date was 16 April which means that the public IP will be able to continue for 2 weeks after the last renew (30 April).

**Comment by xmonader** [comment]
related to https://github.com/threefoldtech/zos/issues/1268
