### ISSUE TITLE
threefold connect gets stuck

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/itenv_testnet#5]
from the testers chat user Enigma

![image](https://user-images.githubusercontent.com/64129/116818686-f890f800-ab6c-11eb-8989-4d67da5ca1ab.png)

Enigma:
Hi. I'm stuck on the authenticate part. Is something supposed to pop up in my threefold connect app? App is set up with id and tft in wallet. Am I supposed to logout in the app somehow first?

xmonader: Enigma you need to hve the app open otherwise it won't work

Enigma: 
Yeah app is open. Nothing pops up. I've tried going to settings, wallet, and home...but can't see anything to authenticate. 
Also just to confirm...when browser page asks for my ID, it is just the first part I type in not the entire ID with the .3bot?

**Comment by friedger** [comment]
I saw this as well. Closing and reopening the Android app resolved the issue.
