### ISSUE TITLE
No access to K8S in my vdc

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#7]
Workload disappeared from my VDC, and I see quite some alerts that it is able to connect to the server

3bot: geertincubaid
vdc: vdcdiamondnode

![image](https://user-images.githubusercontent.com/30384423/117433497-d233d980-af2b-11eb-9f32-9c0f53b8b01c.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/117456528-95c2a680-af48-11eb-9f0c-f7bc5a581aef.png)

unreachable master ip 185.69.166.183, IP4 units were all consumed 
![image](https://user-images.githubusercontent.com/64129/117456607-ae32c100-af48-11eb-8d80-f4b862a07e13.png)
