### ISSUE TITLE
Access to K8S cluster in VDC suddenly lost (no obvious trigger)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/itenv_testnet#9]
i have a VDC running since 3 days (so it hasn't expired !), but suddenly it started to create alerts. Connection seems to be lost. Looks like it is the case since this morning 3.37am. 

VDC: silver3
3bot: geertincubaid

Alert raised by servicemanager: 
Service vdc_dashboard_k8s_auto_extend raised an exception: Failed to execute: kubectl --kubeconfig /root/.kube/config top nodes --no-headers=true, error was W0518 06:47:41.241976 31308 top_node.go:119] Using json format to get metrics. Next release will switch to protocol-buffers, switch early by passing --use-protocol-buffers flag Unable to connect to the server: dial tcp 185.69.166.147:6443: connect: no route to host

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/118645087-c921f280-b7de-11eb-9e88-301f962720b3.png)

Kubernetes master node is down Hx4B6B8s8yQ5ABLStma1kZ33kCuprSxzU8tY4totKbWH

**Comment by sabrinasadik** [comment]
RAM usage suddenly at 100% (03.20h last night) 
Need to figure out what caused this @delandtj

**Comment by gmachtel** [comment]
K8S cluster accessible again now, so my issue is solved. But will leave issue open to investigate on RAM issue.

**Comment by sabrinasadik** [comment]
RAM was at 14.5 out of 16. K8S VM reservation of 2GB came it but was not rejected, which it should have done. Need to investigate why the rejection didn't happen

**Comment by sabrinasadik** [comment]
Closing this issue, follow up on https://github.com/threefoldtech/zos/issues/1275

**Comment by gmachtel** [comment]
The session was re-established, but the service tried to withdraw a bigger amount from the wallet after the reconnection: 

Service vdc_dashboard_provision_wallet_billing raised an exception: Wallet provision_wallet_173e1397a3a149b4b6e39f3d8d0eb52a does not have enough funds to pay for 6.0866467 TFT:GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47

**Comment by gmachtel** [comment]
Next to that, this Vdc was reconnected overnight, but now another wallet got disconnected, also overnight. I create another issue for it ? 

Wallet disconnected: platinum2, 3bot: geertincubaid

**Comment by xmonader** [comment]
closing this one, the last two comments to bee addressed in another issue https://github.com/threefoldtech/itenv_testnet/issues/11
